title: Jekyll Tutorial Blog
email: jekyll@example.com
description: >-
  Our tutorial blog made with Jekyll, deployed with Appliku
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Appliku"
